{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "1836261b-3158-4bb7-bea9-929cf4861d5b",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "\"Using the `Exception` class as the base class when creating a custom exception is a recommended practice in Python. Here's why:\\n\\n1. Inheritance: The `Exception` class serves as the base class for all built-in exceptions in Python. By inheriting from the `Exception` class, your custom exception inherits important behavior and properties from it, such as the ability to be caught by `except` blocks and access to exception handling mechanisms.\\n\\n2. Consistency: Inheriting from the `Exception` class ensures that your custom exception follows the same pattern and conventions as other built-in exceptions. This promotes consistency and familiarity for developers who are already familiar with handling standard exceptions in Python.\\n\\n3. Compatibility: By using the `Exception` class as the base class, your custom exception is compatible with existing exception handling code and libraries that expect exceptions to be derived from the `Exception` class. It allows your custom exception to seamlessly integrate with the existing exception hierarchy.\\n\\n4. Exception Handling: The `Exception` class provides a range of methods and attributes that facilitate exception handling. These include `__str__` for string representation, `__repr__` for a formal representation, and other methods for manipulating and accessing exception information. By inheriting from `Exception`, your custom exception inherits these capabilities, making it easier to handle and present exceptions consistently.\\n\\n5. Clear Intent: By explicitly inheriting from the `Exception` class, you make it clear that your custom class is intended to represent an exception. This helps other developers understand the purpose and behavior of your custom exception without needing to inspect the implementation.\\n\\n\""
      ]
     },
     "execution_count": 1,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "\n",
    "#que1\n",
    "\"\"\"Using the `Exception` class as the base class when creating a custom exception is a recommended practice in Python. Here's why:\n",
    "\n",
    "1. Inheritance: The `Exception` class serves as the base class for all built-in exceptions in Python. By inheriting from the `Exception` class, your custom exception inherits important behavior and properties from it, such as the ability to be caught by `except` blocks and access to exception handling mechanisms.\n",
    "\n",
    "2. Consistency: Inheriting from the `Exception` class ensures that your custom exception follows the same pattern and conventions as other built-in exceptions. This promotes consistency and familiarity for developers who are already familiar with handling standard exceptions in Python.\n",
    "\n",
    "3. Compatibility: By using the `Exception` class as the base class, your custom exception is compatible with existing exception handling code and libraries that expect exceptions to be derived from the `Exception` class. It allows your custom exception to seamlessly integrate with the existing exception hierarchy.\n",
    "\n",
    "4. Exception Handling: The `Exception` class provides a range of methods and attributes that facilitate exception handling. These include `__str__` for string representation, `__repr__` for a formal representation, and other methods for manipulating and accessing exception information. By inheriting from `Exception`, your custom exception inherits these capabilities, making it easier to handle and present exceptions consistently.\n",
    "\n",
    "5. Clear Intent: By explicitly inheriting from the `Exception` class, you make it clear that your custom class is intended to represent an exception. This helps other developers understand the purpose and behavior of your custom exception without needing to inspect the implementation.\n",
    "\n",
    "\"\"\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "42bb1cd1-de8e-467c-880a-1075bc7d366f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Python Exception Hierarchy:\n",
      "<class 'Exception'>\n",
      "  <class 'TypeError'>\n",
      "    <class 'decimal.FloatOperation'>\n",
      "    <class 'email.errors.MultipartConversionError'>\n",
      "  <class 'StopAsyncIteration'>\n",
      "  <class 'StopIteration'>\n",
      "  <class 'ImportError'>\n",
      "    <class 'ModuleNotFoundError'>\n",
      "    <class 'zipimport.ZipImportError'>\n",
      "  <class 'OSError'>\n",
      "    <class 'ConnectionError'>\n",
      "      <class 'BrokenPipeError'>\n",
      "      <class 'ConnectionAbortedError'>\n",
      "      <class 'ConnectionRefusedError'>\n",
      "      <class 'ConnectionResetError'>\n",
      "        <class 'http.client.RemoteDisconnected'>\n",
      "    <class 'BlockingIOError'>\n",
      "    <class 'ChildProcessError'>\n",
      "    <class 'FileExistsError'>\n",
      "    <class 'FileNotFoundError'>\n",
      "    <class 'IsADirectoryError'>\n",
      "    <class 'NotADirectoryError'>\n",
      "    <class 'InterruptedError'>\n",
      "      <class 'zmq.error.InterruptedSystemCall'>\n",
      "    <class 'PermissionError'>\n",
      "    <class 'ProcessLookupError'>\n",
      "    <class 'TimeoutError'>\n",
      "    <class 'io.UnsupportedOperation'>\n",
      "    <class 'signal.itimer_error'>\n",
      "    <class 'socket.herror'>\n",
      "    <class 'socket.gaierror'>\n",
      "    <class 'ssl.SSLError'>\n",
      "      <class 'ssl.SSLCertVerificationError'>\n",
      "      <class 'ssl.SSLZeroReturnError'>\n",
      "      <class 'ssl.SSLWantWriteError'>\n",
      "      <class 'ssl.SSLWantReadError'>\n",
      "      <class 'ssl.SSLSyscallError'>\n",
      "      <class 'ssl.SSLEOFError'>\n",
      "    <class 'shutil.Error'>\n",
      "      <class 'shutil.SameFileError'>\n",
      "    <class 'shutil.SpecialFileError'>\n",
      "    <class 'shutil.ExecError'>\n",
      "    <class 'shutil.ReadError'>\n",
      "    <class 'urllib.error.URLError'>\n",
      "      <class 'urllib.error.HTTPError'>\n",
      "      <class 'urllib.error.ContentTooShortError'>\n",
      "    <class 'gzip.BadGzipFile'>\n",
      "  <class 'EOFError'>\n",
      "    <class 'asyncio.exceptions.IncompleteReadError'>\n",
      "  <class 'RuntimeError'>\n",
      "    <class 'RecursionError'>\n",
      "    <class 'NotImplementedError'>\n",
      "      <class 'zmq.error.ZMQVersionError'>\n",
      "      <class 'IPython.core.error.StdinNotImplementedError'>\n",
      "    <class '_frozen_importlib._DeadlockError'>\n",
      "    <class 'threading.BrokenBarrierError'>\n",
      "    <class 'concurrent.futures._base.BrokenExecutor'>\n",
      "      <class 'concurrent.futures.thread.BrokenThreadPool'>\n",
      "    <class 'asyncio.exceptions.SendfileNotAvailableError'>\n",
      "    <class 'pkg_resources.ExtractionError'>\n",
      "    <class '_pydevd_bundle.pydevd_vars.VariableError'>\n",
      "  <class 'NameError'>\n",
      "    <class 'UnboundLocalError'>\n",
      "  <class 'AttributeError'>\n",
      "    <class 'dataclasses.FrozenInstanceError'>\n",
      "  <class 'SyntaxError'>\n",
      "    <class 'IndentationError'>\n",
      "      <class 'TabError'>\n",
      "  <class 'LookupError'>\n",
      "    <class 'IndexError'>\n",
      "    <class 'KeyError'>\n",
      "      <class 'jupyter_client.kernelspec.NoSuchKernel'>\n",
      "      <class 'IPython.terminal.pt_inputhooks.UnknownBackend'>\n",
      "    <class 'encodings.CodecRegistryError'>\n",
      "  <class 'ValueError'>\n",
      "    <class 'UnicodeError'>\n",
      "      <class 'UnicodeEncodeError'>\n",
      "      <class 'UnicodeDecodeError'>\n",
      "      <class 'UnicodeTranslateError'>\n",
      "    <class 'io.UnsupportedOperation'>\n",
      "    <class 'json.decoder.JSONDecodeError'>\n",
      "    <class 'ssl.SSLCertVerificationError'>\n",
      "    <class 'binascii.Error'>\n",
      "    <class '_hashlib.UnsupportedDigestmodError'>\n",
      "    <class 'calendar.IllegalMonthError'>\n",
      "    <class 'calendar.IllegalWeekdayError'>\n",
      "    <class 'dateutil.parser._parser.ParserError'>\n",
      "    <class 'pygments.util.ClassNotFound'>\n",
      "    <class 'IPython.lib.clipboard.ClipboardEmpty'>\n",
      "    <class 'email.errors.MessageDefect'>\n",
      "      <class 'email.errors.NoBoundaryInMultipartDefect'>\n",
      "      <class 'email.errors.StartBoundaryNotFoundDefect'>\n",
      "      <class 'email.errors.CloseBoundaryNotFoundDefect'>\n",
      "      <class 'email.errors.FirstHeaderLineIsContinuationDefect'>\n",
      "      <class 'email.errors.MisplacedEnvelopeHeaderDefect'>\n",
      "      <class 'email.errors.MissingHeaderBodySeparatorDefect'>\n",
      "      <class 'email.errors.MultipartInvariantViolationDefect'>\n",
      "      <class 'email.errors.InvalidMultipartContentTransferEncodingDefect'>\n",
      "      <class 'email.errors.UndecodableBytesDefect'>\n",
      "      <class 'email.errors.InvalidBase64PaddingDefect'>\n",
      "      <class 'email.errors.InvalidBase64CharactersDefect'>\n",
      "      <class 'email.errors.InvalidBase64LengthDefect'>\n",
      "      <class 'email.errors.HeaderDefect'>\n",
      "        <class 'email.errors.InvalidHeaderDefect'>\n",
      "        <class 'email.errors.HeaderMissingRequiredValue'>\n",
      "        <class 'email.errors.NonPrintableDefect'>\n",
      "        <class 'email.errors.ObsoleteHeaderDefect'>\n",
      "        <class 'email.errors.NonASCIILocalPartDefect'>\n",
      "        <class 'email.errors.InvalidDateDefect'>\n",
      "    <class 'IPython.core.magics.code.MacroToEdit'>\n",
      "    <class 'plistlib.InvalidFileException'>\n",
      "    <class 'pkg_resources._vendor.more_itertools.more.UnequalIterablesError'>\n",
      "    <class 'pkg_resources.extern.packaging.version.InvalidVersion'>\n",
      "    <class 'pkg_resources._vendor.packaging._manylinux._ELFFileHeader._InvalidELFFileHeader'>\n",
      "    <class 'pkg_resources.extern.packaging.utils.InvalidWheelFilename'>\n",
      "    <class 'pkg_resources.extern.packaging.utils.InvalidSdistFilename'>\n",
      "    <class 'pkg_resources.extern.packaging.specifiers.InvalidSpecifier'>\n",
      "    <class 'pkg_resources.extern.packaging.markers.InvalidMarker'>\n",
      "    <class 'pkg_resources.extern.packaging.markers.UndefinedComparison'>\n",
      "    <class 'pkg_resources.extern.packaging.markers.UndefinedEnvironmentName'>\n",
      "    <class 'pkg_resources.extern.packaging.requirements.InvalidRequirement'>\n",
      "      <class 'pkg_resources.RequirementParseError'>\n",
      "    <class 'packaging.version.InvalidVersion'>\n",
      "  <class 'AssertionError'>\n",
      "  <class 'ArithmeticError'>\n",
      "    <class 'FloatingPointError'>\n",
      "    <class 'OverflowError'>\n",
      "    <class 'ZeroDivisionError'>\n",
      "      <class 'decimal.DivisionByZero'>\n",
      "      <class 'decimal.DivisionUndefined'>\n",
      "    <class 'decimal.DecimalException'>\n",
      "      <class 'decimal.Clamped'>\n",
      "      <class 'decimal.Rounded'>\n",
      "        <class 'decimal.Underflow'>\n",
      "        <class 'decimal.Overflow'>\n",
      "      <class 'decimal.Inexact'>\n",
      "        <class 'decimal.Underflow'>\n",
      "        <class 'decimal.Overflow'>\n",
      "      <class 'decimal.Subnormal'>\n",
      "        <class 'decimal.Underflow'>\n",
      "      <class 'decimal.DivisionByZero'>\n",
      "      <class 'decimal.FloatOperation'>\n",
      "      <class 'decimal.InvalidOperation'>\n",
      "        <class 'decimal.ConversionSyntax'>\n",
      "        <class 'decimal.DivisionImpossible'>\n",
      "        <class 'decimal.DivisionUndefined'>\n",
      "        <class 'decimal.InvalidContext'>\n",
      "  <class 'SystemError'>\n",
      "    <class 'encodings.CodecRegistryError'>\n",
      "  <class 'ReferenceError'>\n",
      "  <class 'MemoryError'>\n",
      "  <class 'BufferError'>\n",
      "  <class 'Warning'>\n",
      "    <class 'UserWarning'>\n",
      "      <class 'getpass.GetPassWarning'>\n",
      "      <class 'IPython.core.formatters.FormatterWarning'>\n",
      "    <class 'EncodingWarning'>\n",
      "    <class 'DeprecationWarning'>\n",
      "      <class 'IPython.core.interactiveshell.ProvisionalWarning'>\n",
      "    <class 'PendingDeprecationWarning'>\n",
      "    <class 'SyntaxWarning'>\n",
      "    <class 'RuntimeWarning'>\n",
      "      <class 'zmq.asyncio.ProactorSelectorThreadWarning'>\n",
      "      <class 'dateutil.parser._parser.UnknownTimezoneWarning'>\n",
      "      <class 'pkg_resources.PEP440Warning'>\n",
      "    <class 'FutureWarning'>\n",
      "      <class 'IPython.core.completer.ProvisionalCompleterWarning'>\n",
      "    <class 'ImportWarning'>\n",
      "    <class 'UnicodeWarning'>\n",
      "    <class 'BytesWarning'>\n",
      "    <class 'ResourceWarning'>\n",
      "    <class 'dateutil.tz.DeprecatedTzFormatWarning'>\n",
      "    <class 'pkg_resources.PkgResourcesDeprecationWarning'>\n",
      "  <class 'warnings._OptionError'>\n",
      "  <class 'runpy._Error'>\n",
      "  <class 're.error'>\n",
      "  <class 'sre_parse.Verbose'>\n",
      "  <class 'locale.Error'>\n",
      "  <class 'subprocess.SubprocessError'>\n",
      "    <class 'subprocess.CalledProcessError'>\n",
      "    <class 'subprocess.TimeoutExpired'>\n",
      "  <class 'tokenize.TokenError'>\n",
      "  <class 'tokenize.StopTokenizing'>\n",
      "  <class 'inspect.ClassFoundException'>\n",
      "  <class 'inspect.EndOfBlock'>\n",
      "  <class 'traitlets.traitlets.TraitError'>\n",
      "  <class 'copy.Error'>\n",
      "  <class 'concurrent.futures._base.Error'>\n",
      "    <class 'concurrent.futures._base.CancelledError'>\n",
      "    <class 'concurrent.futures._base.TimeoutError'>\n",
      "    <class 'concurrent.futures._base.InvalidStateError'>\n",
      "  <class 'socket._GiveupOnSendfile'>\n",
      "  <class 'struct.error'>\n",
      "  <class 'binascii.Incomplete'>\n",
      "  <class 'asyncio.exceptions.TimeoutError'>\n",
      "  <class 'asyncio.exceptions.InvalidStateError'>\n",
      "  <class 'asyncio.exceptions.LimitOverrunError'>\n",
      "  <class 'asyncio.queues.QueueEmpty'>\n",
      "  <class 'asyncio.queues.QueueFull'>\n",
      "  <class '_queue.Empty'>\n",
      "  <class 'queue.Full'>\n",
      "  <class 'ctypes.ArgumentError'>\n",
      "  <class 'zmq.error.ZMQBaseError'>\n",
      "    <class 'zmq.error.ZMQError'>\n",
      "      <class 'zmq.error.ContextTerminated'>\n",
      "      <class 'zmq.error.Again'>\n",
      "      <class 'zmq.error.InterruptedSystemCall'>\n",
      "    <class 'zmq.error.ZMQBindError'>\n",
      "    <class 'zmq.error.NotDone'>\n",
      "  <class '_pickle.PickleError'>\n",
      "    <class '_pickle.PicklingError'>\n",
      "    <class '_pickle.UnpicklingError'>\n",
      "  <class 'pickle._Stop'>\n",
      "  <class 'argparse.ArgumentError'>\n",
      "  <class 'argparse.ArgumentTypeError'>\n",
      "  <class 'traitlets.config.loader.ConfigError'>\n",
      "    <class 'traitlets.config.loader.ConfigLoaderError'>\n",
      "      <class 'traitlets.config.loader.ArgumentError'>\n",
      "    <class 'traitlets.config.loader.ConfigFileNotFound'>\n",
      "  <class 'traitlets.config.configurable.ConfigurableError'>\n",
      "    <class 'traitlets.config.configurable.MultipleInstanceError'>\n",
      "  <class 'traitlets.config.application.ApplicationError'>\n",
      "  <class 'zlib.error'>\n",
      "  <class 'tornado.util.TimeoutError'>\n",
      "  <class '_curses.error'>\n",
      "  <class 'tornado.concurrent.ReturnValueIgnoredError'>\n",
      "  <class 'tornado.gen.KeyReuseError'>\n",
      "  <class 'tornado.gen.UnknownKeyError'>\n",
      "  <class 'tornado.gen.LeakedCallbackError'>\n",
      "  <class 'tornado.gen.BadYieldError'>\n",
      "  <class 'tornado.gen.ReturnValueIgnoredError'>\n",
      "  <class 'tornado.gen.Return'>\n",
      "  <class 'jupyter_client.channels.InvalidPortNumber'>\n",
      "  <class 'termios.error'>\n",
      "  <class '_lzma.LZMAError'>\n",
      "  <class 'shutil.RegistryError'>\n",
      "  <class 'shutil._GiveupOnFastCopy'>\n",
      "  <class 'configparser.Error'>\n",
      "    <class 'configparser.NoSectionError'>\n",
      "    <class 'configparser.DuplicateSectionError'>\n",
      "    <class 'configparser.DuplicateOptionError'>\n",
      "    <class 'configparser.NoOptionError'>\n",
      "    <class 'configparser.InterpolationError'>\n",
      "      <class 'configparser.InterpolationMissingOptionError'>\n",
      "      <class 'configparser.InterpolationSyntaxError'>\n",
      "      <class 'configparser.InterpolationDepthError'>\n",
      "    <class 'configparser.ParsingError'>\n",
      "      <class 'configparser.MissingSectionHeaderError'>\n",
      "  <class 'jupyter_client.localinterfaces.NoIPAddresses'>\n",
      "  <class 'zipfile.BadZipFile'>\n",
      "  <class 'zipfile.LargeZipFile'>\n",
      "  <class 'entrypoints.BadEntryPoint'>\n",
      "  <class 'entrypoints.NoSuchEntryPoint'>\n",
      "  <class 'jupyter_client.multikernelmanager.DuplicateKernelError'>\n",
      "  <class 'pydoc.ErrorDuringImport'>\n",
      "  <class 'executing.executing.NotOneValueFound'>\n",
      "  <class 'pure_eval.utils.CannotEval'>\n",
      "  <class 'pygments.util.OptionError'>\n",
      "  <class 'bdb.BdbQuit'>\n",
      "  <class 'pdb.Restart'>\n",
      "  <class 'pexpect.exceptions.ExceptionPexpect'>\n",
      "    <class 'pexpect.exceptions.EOF'>\n",
      "    <class 'pexpect.exceptions.TIMEOUT'>\n",
      "  <class 'ptyprocess.util.PtyProcessError'>\n",
      "  <class 'IPython.utils.process.FindCmdError'>\n",
      "  <class 'IPython.utils.path.HomeDirError'>\n",
      "  <class 'IPython.core.profiledir.ProfileDirError'>\n",
      "  <class 'IPython.core.error.IPythonCoreError'>\n",
      "    <class 'IPython.core.error.TryNext'>\n",
      "    <class 'IPython.core.error.UsageError'>\n",
      "    <class 'IPython.core.error.StdinNotImplementedError'>\n",
      "  <class 'IPython.core.error.InputRejected'>\n",
      "  <class 'getopt.GetoptError'>\n",
      "  <class 'pygments.filters.ErrorToken'>\n",
      "  <class 'IPython.core.prefilter.PrefilterError'>\n",
      "  <class 'IPython.core.alias.AliasError'>\n",
      "    <class 'IPython.core.alias.InvalidAliasError'>\n",
      "  <class 'sqlite3.Error'>\n",
      "    <class 'sqlite3.InterfaceError'>\n",
      "    <class 'sqlite3.DatabaseError'>\n",
      "      <class 'sqlite3.InternalError'>\n",
      "      <class 'sqlite3.OperationalError'>\n",
      "      <class 'sqlite3.ProgrammingError'>\n",
      "      <class 'sqlite3.IntegrityError'>\n",
      "      <class 'sqlite3.DataError'>\n",
      "      <class 'sqlite3.NotSupportedError'>\n",
      "  <class 'sqlite3.Warning'>\n",
      "  <class 'IPython.core.interactiveshell.SpaceInInput'>\n",
      "  <class 'xml.dom.DOMException'>\n",
      "    <class 'xml.dom.IndexSizeErr'>\n",
      "    <class 'xml.dom.DomstringSizeErr'>\n",
      "    <class 'xml.dom.HierarchyRequestErr'>\n",
      "    <class 'xml.dom.WrongDocumentErr'>\n",
      "    <class 'xml.dom.InvalidCharacterErr'>\n",
      "    <class 'xml.dom.NoDataAllowedErr'>\n",
      "    <class 'xml.dom.NoModificationAllowedErr'>\n",
      "    <class 'xml.dom.NotFoundErr'>\n",
      "    <class 'xml.dom.NotSupportedErr'>\n",
      "    <class 'xml.dom.InuseAttributeErr'>\n",
      "    <class 'xml.dom.InvalidStateErr'>\n",
      "    <class 'xml.dom.SyntaxErr'>\n",
      "    <class 'xml.dom.InvalidModificationErr'>\n",
      "    <class 'xml.dom.NamespaceErr'>\n",
      "    <class 'xml.dom.InvalidAccessErr'>\n",
      "    <class 'xml.dom.ValidationErr'>\n",
      "  <class 'prompt_toolkit.validation.ValidationError'>\n",
      "  <class 'prompt_toolkit.buffer.EditReadOnlyBuffer'>\n",
      "  <class 'prompt_toolkit.buffer._Retry'>\n",
      "  <class 'prompt_toolkit.layout.layout.InvalidLayoutError'>\n",
      "  <class 'prompt_toolkit.renderer.HeightIsUnknownError'>\n",
      "  <class 'parso.parser.ParserSyntaxError'>\n",
      "  <class 'parso.parser.InternalParseError'>\n",
      "  <class 'parso.python.diff._PositionUpdatingFinished'>\n",
      "  <class 'jedi.inference.helpers.SimpleGetItemNotFound'>\n",
      "  <class 'jedi.inference.utils.UncaughtAttributeError'>\n",
      "  <class 'jedi.inference.base_value.HasNoContext'>\n",
      "  <class 'jedi.inference.arguments.ParamIssue'>\n",
      "  <class 'jedi.api.exceptions._JediError'>\n",
      "    <class 'jedi.api.exceptions.InternalError'>\n",
      "    <class 'jedi.api.exceptions.WrongVersion'>\n",
      "    <class 'jedi.api.exceptions.RefactoringError'>\n",
      "  <class 'jedi.api.helpers.OnErrorLeaf'>\n",
      "  <class 'jedi.api.environment.InvalidPythonEnvironment'>\n",
      "  <class 'email.errors.MessageError'>\n",
      "    <class 'email.errors.MessageParseError'>\n",
      "      <class 'email.errors.HeaderParseError'>\n",
      "      <class 'email.errors.BoundaryError'>\n",
      "    <class 'email.errors.MultipartConversionError'>\n",
      "    <class 'email.errors.CharsetError'>\n",
      "  <class 'uu.Error'>\n",
      "  <class 'http.client.HTTPException'>\n",
      "    <class 'http.client.NotConnected'>\n",
      "    <class 'http.client.InvalidURL'>\n",
      "    <class 'http.client.UnknownProtocol'>\n",
      "    <class 'http.client.UnknownTransferEncoding'>\n",
      "    <class 'http.client.UnimplementedFileMode'>\n",
      "    <class 'http.client.IncompleteRead'>\n",
      "    <class 'http.client.ImproperConnectionState'>\n",
      "      <class 'http.client.CannotSendRequest'>\n",
      "      <class 'http.client.CannotSendHeader'>\n",
      "      <class 'http.client.ResponseNotReady'>\n",
      "    <class 'http.client.BadStatusLine'>\n",
      "      <class 'http.client.RemoteDisconnected'>\n",
      "    <class 'http.client.LineTooLong'>\n",
      "  <class 'IPython.core.magics.code.InteractivelyDefined'>\n",
      "  <class 'IPython.terminal.embed.KillEmbedded'>\n",
      "  <class 'psutil.Error'>\n",
      "    <class 'psutil.NoSuchProcess'>\n",
      "      <class 'psutil.ZombieProcess'>\n",
      "    <class 'psutil.AccessDenied'>\n",
      "    <class 'psutil.TimeoutExpired'>\n",
      "  <class 'psutil._pslinux._Ipv6UnsupportedError'>\n",
      "  <class 'tornado.queues.QueueEmpty'>\n",
      "  <class 'tornado.queues.QueueFull'>\n",
      "  <class '_pydev_bundle._pydev_saved_modules.DebuggerInitializationError'>\n",
      "  <class 'xml.parsers.expat.ExpatError'>\n",
      "  <class 'xmlrpc.client.Error'>\n",
      "    <class 'xmlrpc.client.ProtocolError'>\n",
      "    <class 'xmlrpc.client.ResponseError'>\n",
      "    <class 'xmlrpc.client.Fault'>\n",
      "  <class 'pkg_resources._vendor.pyparsing.exceptions.ParseBaseException'>\n",
      "    <class 'pkg_resources._vendor.pyparsing.exceptions.ParseException'>\n",
      "    <class 'pkg_resources._vendor.pyparsing.exceptions.ParseFatalException'>\n",
      "      <class 'pkg_resources._vendor.pyparsing.exceptions.ParseSyntaxException'>\n",
      "  <class 'pkg_resources._vendor.pyparsing.exceptions.RecursiveGrammarException'>\n",
      "  <class 'pkg_resources.ResolutionError'>\n",
      "    <class 'pkg_resources.VersionConflict'>\n",
      "      <class 'pkg_resources.ContextualVersionConflict'>\n",
      "    <class 'pkg_resources.DistributionNotFound'>\n",
      "    <class 'pkg_resources.UnknownExtra'>\n",
      "  <class '_pydevd_bundle.pydevd_runpy._Error'>\n",
      "  <class '_pydevd_bundle.pydevd_resolver.UnableToResolveVariableException'>\n",
      "  <class '_pydev_bundle.pydev_monkey.InvalidTypeInArgsException'>\n"
     ]
    }
   ],
   "source": [
    "#que 2\n",
    "def print_exception_hierarchy(exception_class, indent=0):\n",
    "    print(' ' * indent + str(exception_class))\n",
    "    for subclass in exception_class.__subclasses__():\n",
    "        print_exception_hierarchy(subclass, indent + 2)\n",
    "\n",
    "\n",
    "# Print the Exception Hierarchy\n",
    "print(\"Python Exception Hierarchy:\")\n",
    "print_exception_hierarchy(Exception)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "8ca8a2e5-fb11-46c4-be9d-73f3b0b3b003",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error: Division by zero is not allowed!\n",
      "None\n"
     ]
    }
   ],
   "source": [
    "#que 3\n",
    "#The ArithmeticError class in Python is a base class for exceptions that occur during arithmetic operations. It is a subclass of the Exception class and serves as a parent class for specific arithmetic-related exceptions. Two commonly used exceptions derived from ArithmeticError are ZeroDivisionError and OverflowError.\n",
    "\n",
    "#examples\n",
    "def divide_numbers(a, b):\n",
    "    try:\n",
    "        result = a / b\n",
    "        return result\n",
    "    except ZeroDivisionError:\n",
    "        print(\"Error: Division by zero is not allowed!\")\n",
    "\n",
    "\n",
    "# Example: Division by Zero\n",
    "result = divide_numbers(10, 0)\n",
    "print(result)\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "8cea8f6c-db30-4d32-aa9d-b7c39e946f88",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "402387260077093773543702433923003985719374864210714632543799910429938512398629020592044208486969404800479988610197196058631666872994808558901323829669944590997424504087073759918823627727188732519779505950995276120874975462497043601418278094646496291056393887437886487337119181045825783647849977012476632889835955735432513185323958463075557409114262417474349347553428646576611667797396668820291207379143853719588249808126867838374559731746136085379534524221586593201928090878297308431392844403281231558611036976801357304216168747609675871348312025478589320767169132448426236131412508780208000261683151027341827977704784635868170164365024153691398281264810213092761244896359928705114964975419909342221566832572080821333186116811553615836546984046708975602900950537616475847728421889679646244945160765353408198901385442487984959953319101723355556602139450399736280750137837615307127761926849034352625200015888535147331611702103968175921510907788019393178114194545257223865541461062892187960223838971476088506276862967146674697562911234082439208160153780889893964518263243671616762179168909779911903754031274622289988005195444414282012187361745992642956581746628302955570299024324153181617210465832036786906117260158783520751516284225540265170483304226143974286933061690897968482590125458327168226458066526769958652682272807075781391858178889652208164348344825993266043367660176999612831860788386150279465955131156552036093988180612138558600301435694527224206344631797460594682573103790084024432438465657245014402821885252470935190620929023136493273497565513958720559654228749774011413346962715422845862377387538230483865688976461927383814900140767310446640259899490222221765904339901886018566526485061799702356193897017860040811889729918311021171229845901641921068884387121855646124960798722908519296819372388642614839657382291123125024186649353143970137428531926649875337218940694281434118520158014123344828015051399694290153483077644569099073152433278288269864602789864321139083506217095002597389863554277196742822248757586765752344220207573630569498825087968928162753848863396909959826280956121450994871701244516461260379029309120889086942028510640182154399457156805941872748998094254742173582401063677404595741785160829230135358081840096996372524230560855903700624271243416909004153690105933983835777939410970027753472000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000\n"
     ]
    }
   ],
   "source": [
    "def calculate_factorial(n):\n",
    "    try:\n",
    "        result = 1\n",
    "        for i in range(1, n+1):\n",
    "            result *= i\n",
    "        return result\n",
    "    except OverflowError:\n",
    "        print(\"Error: The factorial is too large to calculate!\")\n",
    "\n",
    "\n",
    "# Example: Calculating Factorial\n",
    "factorial = calculate_factorial(1000)\n",
    "print(factorial)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "13f0c3a2-62d3-4279-a40c-a6e7eefead75",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error: Key 'd' does not exist in the dictionary!\n",
      "None\n"
     ]
    }
   ],
   "source": [
    "#que 4\n",
    "#The LookupError class in Python is a base class for exceptions that occur when a lookup or indexing operation fails. It is a subclass of the Exception class and serves as a parent class for specific lookup-related exceptions. \n",
    "\n",
    "def get_dictionary_value(dictionary, key):\n",
    "    try:\n",
    "        value = dictionary[key]\n",
    "        return value\n",
    "    except KeyError:\n",
    "        print(f\"Error: Key '{key}' does not exist in the dictionary!\")\n",
    "\n",
    "\n",
    "# Example: Dictionary Lookup\n",
    "my_dict = {'a': 1, 'b': 2, 'c': 3}\n",
    "value = get_dictionary_value(my_dict, 'd')\n",
    "print(value)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "89581a6b-b93f-4633-b302-a6727aa1dbf7",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error: Index '5' is out of range for the list!\n",
      "None\n"
     ]
    }
   ],
   "source": [
    "def get_list_item(lst, index):\n",
    "    try:\n",
    "        item = lst[index]\n",
    "        return item\n",
    "    except IndexError:\n",
    "        print(f\"Error: Index '{index}' is out of range for the list!\")\n",
    "\n",
    "\n",
    "# Example: List Indexing\n",
    "my_list = [1, 2, 3]\n",
    "item = get_list_item(my_list, 5)\n",
    "print(item)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1ca75925-a4af-41d1-b73f-f2ddc25b2eed",
   "metadata": {},
   "outputs": [],
   "source": [
    "#que \n",
    "#ImportError and ModuleNotFoundError are related exceptions in Python that occur when importing modules or packages"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
